---
title: "My First Post using {distill}"
description: |
  Lets talk distill, My review of this amazing package.
author:
  - name: Emmanuel Ugochukwu
date: 03-04-2021
preview: burga.png
output:
  distill::distill_article:
    self_contained: false
twitter:
  site: "@anuel"
  creator: "@anuel"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<p> At midnight i installed the **{distill}** on my windows PC while carefully following the instructions laid by Lisa Lindaway in her YouTube video, I found it really easy to use since i already had experience working with R Markdown.</p>
<p> I created the website using the _create_website()_ function and everything got setup, i then relocated some files from a directory to the main folder where the project was located. Next, i created new markdown page where links to my blog posts would be published, it was really easy!</p>
<p>Although, I learnt how to add a photo in R Markdown.</p>
<p> What i found slightly confusing was the YAML section, it took some time to get used to but it wasn't as hard as i thought it to be. </p>
<p> By 10 am the same day, I came back to my distill project and wrote this review. </p>

