---
title: "How I learnt Spanish"
description: |
  My love story with the latin language.
author:
  - name: Emmanuel Ugochukwu
    url: {}
date: 03-04-2021
preview: logo.png
output:
  distill::distill_article:
    self_contained: false
twitter:
  site: "@anuel"
  creator: "@anuel"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Hola!<br>
Buenos Dias mi gente <br>
As you know, it has been 6 months since I started studying Spanish. It has had its ups and downs. I have made a lot of friends in the Latin American and Spanish community. One thing to consider is that I have never been to any country that speaks Spanish in my life. This post is to tell you all that has happened from day 1 to this present day.<br><br>
It all started officially late November, 2019. I said officially because I have always wanted to learn the language and before then, I already knew some basic words in Spanish and was already indirectly exposing myself to Spanish contents and the Spanish culture. So, you could call me an upgraded novice. I started a four months challenge organized by one Ikenna Obi, a fellow language learner who has a YouTube channel, who so inspired me to start learning. 
Well, you know how it started. <br><br>
What next did I do? <br>
Lets dive in, Shall we? <br>
I started to make research on better ways to learn Spanish, my goal was and still is to learn Spanish without paying. I’m a student who has a lot of bills to pay and doesn't want to add to it yet. So, I started using applications like, Duolingo, Busuu, Google Translator and some free materials on the internet. Later on, I joined a WhatsApp community of Spanish learners and I began to make friends. A friend of mine from India who was also learning the language introduced me to this textbook, “Easy Spanish” and this book made me a better student of the language. <br>
 I made sure I was always active in my community and yeah, I made a lot of mistakes but I was corrected and life went on. It wasn’t easy balancing language learning and school work together. I had to mix the Spanish world and my own world together. <br><br>
Was it really possible? <br>
Hell yeah! What did I do? <br>
I changed the language interface of my device to Spanish.<br>
 Was it easy at first? <br>
Well, I deleted my WhatsApp chats one day. Well, I saw it as a good thing because I don’t think I will ever forget the word “Borrar”. Its quite impossible to tell you everything that has happened since November, 2019. But, I can tell you that it has been the best decision and commitment I have ever made.<br><br>
Moving on, I started to make a lot of Spanish friends and joined other Spanish communities. I kept my streaks on Duolingo. <br>
4 months passed and my challenge has ended. But did I know all the Spanish in the world? <br>
No!! <br> 
How much did I know, how will I know if the challenge was really effective?? <br>
I needed a solution to these questions. <br> 
Was I able to find a solution?? <br>
Si, Claro. The solution was right there. I went back to goal. I want to learn the Spanish language. 
You can’t learn a language and not speak a little right?? I needed to start talking to native speakers. <br><br>
It wasn’t easy getting someone to talk to. Many people are ashamed of talking in their target language. A concept I didn’t understand until later. A topic we will discuss in another post.
After some research, I found a website where you get paired with different people(Spanish) from different parts of the world learning your native language (English). <br><br>
Well, I was really nervous when I had my first language session, but I was really surprised when I was speaking with him, he understood all what i said and I understood basically 70% of what he said. The conversation was like a game of tennis only that there were a few smashes.	<br><br>
After that day, I started looking for more friends to practice with and now I have over 10 friends that I can practice Spanish with and a very active Spanish community. <br>
Is that all you need to do to get fluent in Spanish? <br>
For now, I cant say because that's where I am presently. <br>
 My love for Spanish grows everyday. <br>
 What is that thing that makes you fall in love over and over again. Discover it, Nurture it, Train it and watch where it takes you. <br>

Leave your thoughts and suggestions in the comment section. <br>
Gracias!


